[package]
name = "file-service-backend"
version = "0.1.0"
edition = "2024"

[dependencies]
# API crate with server feature
file-service-api = { path = "../file-service-api", features = ["server"] }

# Core dependencies
axum = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tower = { workspace = true }
tower-http = { workspace = true, features = ["cors", "fs"] }

# Authentication
ras-auth-core = { path = "../../../crates/core/ras-auth-core" }
async-trait = { workspace = true }

# Serialization
serde = { workspace = true }
serde_json = { workspace = true }

# JWT dependencies (required by SessionConfig)
chrono = { workspace = true }
jsonwebtoken = { workspace = true }

# Error handling
thiserror = { workspace = true }
anyhow = { workspace = true }

# File handling
uuid = { workspace = true, features = ["v4", "serde"] }
tokio-util = { workspace = true }
mime_guess = { workspace = true }

# Logging
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

# Configuration
dotenvy = { workspace = true }

[build-dependencies]
file-service-api = { path = "../file-service-api", features = ["server"] }