[package]
name = "google-oauth-example"
version = "0.1.1"
edition = "2024"
publish = false

[lib]
path = "src/lib.rs"

[dependencies]
# JSON-RPC infrastructure
ras-jsonrpc-macro = { path = "../../crates/libs/ras-jsonrpc-macro" }
ras-jsonrpc-core = { path = "../../crates/libs/ras-jsonrpc-core" }
ras-jsonrpc-types = { path = "../../crates/libs/ras-jsonrpc-types" }

# Identity management
ras-identity-core = { path = "../../crates/identity/ras-identity-core" }
ras-identity-oauth2 = { path = "../../crates/identity/ras-identity-oauth2" }
ras-identity-session = { path = "../../crates/identity/ras-identity-session" }

# Web framework and utilities
axum = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
anyhow = { workspace = true }
async-trait = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
jsonwebtoken = { workspace = true }
schemars.workspace = true

# Additional dependencies for this example
tracing-subscriber = "0.3"
tower = "0.5"
tower-http = { version = "0.6", features = ["fs", "cors"] }
dotenvy = "0.15"
mime_guess = "2.0"