[package]
name = "rest-backend"
version = "0.1.0"
edition = "2024"

[build-dependencies]
rest-api = { path = "../rest-api", features = ["server"] }

[dependencies]
rest-api = { path = "../rest-api", features = ["server"] }
ras-auth-core = { path = "../../../crates/core/ras-auth-core" }
ras-rest-core = { path = "../../../crates/rest/ras-rest-core" }
axum = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tower = { workspace = true }
tower-http = { workspace = true, features = ["cors"] }
http = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
uuid = { workspace = true, features = ["v4", "serde"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
async-trait = { workspace = true }
anyhow = { workspace = true }