[package]
name = "rust-identity-oauth2"
version = "0.1.0"
edition = "2024"

[dependencies]
rust-identity-core = { path = "../rust-identity-core" }

async-trait = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }