[package]
name = "openrpc-to-bruno"
version = "0.1.0"
edition = "2024"
description = "CLI tool to convert OpenRPC specifications to Bruno API collections"
authors = ["Rust Agent Stack Contributors"]

[[bin]]
name = "openrpc-to-bruno"
path = "src/main.rs"

[lib]
name = "openrpc_to_bruno"
path = "src/lib.rs"

[dependencies]
# CLI parsing
clap = { workspace = true }

# Error handling
thiserror = { workspace = true }
anyhow = { workspace = true }

# Serialization
serde = { workspace = true }
serde_json = { workspace = true }

# OpenRPC types
openrpc-types = { path = "../../libs/openrpc-types" }

# File system operations
tokio = { workspace = true }

[dev-dependencies]
tokio-test = { workspace = true }
tempfile = "3.0"