[package]
name = "rest-api"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
ras-rest-macro = { path = "../../../crates/rest/ras-rest-macro" }
ras-auth-core = { path = "../../../crates/core/ras-auth-core" }
ras-rest-core = { path = "../../../crates/rest/ras-rest-core" }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
schemars = { workspace = true }
tracing.workspace = true
async-trait = { workspace = true }
thiserror = { workspace = true }
wasm-bindgen = { version = "0.2", optional = true }
wasm-bindgen-futures = { version = "0.4", optional = true }
js-sys = { version = "0.3", optional = true }
web-sys = { version = "0.3", optional = true }
serde-wasm-bindgen = { version = "0.6", optional = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
axum = { workspace = true }
tower = { workspace = true }
http = { workspace = true }
reqwest = { workspace = true }
tokio = { workspace = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
reqwest = { version = "0.12", default-features = false, features = ["json"] }

[features]
default = []
wasm-client = [
    "wasm-bindgen",
    "wasm-bindgen-futures",
    "js-sys",
    "web-sys",
    "serde-wasm-bindgen",
    "ras-rest-macro/client",
]
server = ["ras-rest-macro/server"]
client = ["ras-rest-macro/client"]
