[package]
name = "bidirectional-chat-client"
version = "0.1.0"
edition = "2024"

[dependencies]
# Local dependencies
bidirectional-chat-api = { path = "../api" }
ras-jsonrpc-bidirectional-macro = { path = "../../../crates/libs/ras-jsonrpc-bidirectional-macro" }
ras-jsonrpc-bidirectional-client = { path = "../../../crates/libs/ras-jsonrpc-bidirectional-client" }

# Workspace dependencies
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
clap = { workspace = true }
anyhow = { workspace = true }
dialoguer = { workspace = true }
console = { workspace = true }
reqwest = { workspace = true }
chrono = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }

[features]
default = ["client"]
client = ["ras-jsonrpc-bidirectional-macro/client"]