[package]
name = "oauth2-demo-server"
version = "0.1.1"
edition = "2024"
publish = false

[dependencies]
oauth2-demo-api = { path = "../api"}
# JSON-RPC infrastructure
ras-jsonrpc-macro = { path = "../../../crates/rpc/ras-jsonrpc-macro" }
ras-jsonrpc-core = { path = "../../../crates/rpc/ras-jsonrpc-core" }
ras-jsonrpc-types = { path = "../../../crates/rpc/ras-jsonrpc-types" }

# Identity management
ras-identity-core = { path = "../../../crates/core/ras-identity-core" }
ras-identity-oauth2 = { path = "../../../crates/identity/ras-identity-oauth2" }
ras-identity-session = { path = "../../../crates/identity/ras-identity-session" }

# Web framework and utilities
axum = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
anyhow = { workspace = true }
async-trait = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
jsonwebtoken = { workspace = true }
schemars.workspace = true

# Additional dependencies for this example
tracing-subscriber = { workspace = true }
tower = { workspace = true }
tower-http = { workspace = true, features = ["fs", "cors"] }
dotenvy = { workspace = true }
mime_guess = { workspace = true }

[build-dependencies]
oauth2-demo-api = { path = "../api"}
serde_json.workspace = true