[package]
name = "ras-identity-oauth2"
version = "0.1.1"
edition = "2024"
description = "OAuth2 authentication provider with Google support, PKCE, and state management"
license = "MIT OR Apache-2.0"
repository = "https://github.com/example/rust-agent-stack"
homepage = "https://github.com/example/rust-agent-stack"

[dependencies]
ras-identity-core = { path = "../../core/ras-identity-core" }

async-trait = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
chrono = { workspace = true }
uuid = { workspace = true }
axum = { workspace = true }

# OAuth2 specific dependencies
reqwest = { workspace = true }
base64 = { workspace = true }
sha2 = { workspace = true }
rand = { workspace = true }
url = { workspace = true }

[dev-dependencies]
tokio-test = { workspace = true }
wiremock = { workspace = true }
tracing-subscriber = { workspace = true }

# For the example
ras-identity-session = { path = "../ras-identity-session" }