[registries.kellnr]
index = "sparse+http://127.0.0.1:8000/api/v1/crates/"
token = "rGHuge8eJbqswR2kaVqlQ9lKYx95MANf"

[registry]
default = "kellnr"

[net]
retry = 3
offline = false

[build]
incremental = true

[profile.debug]
panic = "abort"