[registries]
kellnr = { index = "http://localhost:8000/crate-index/" }
token = "rGHuge8eJbqswR2kaVqlQ9lKYx95MANf"

[registry]
default = "kellnr"

[net]
retry = 3
offline = false

[build]
incremental = true