[package]
name = "rest-service-example"
version = "0.1.0"
edition = "2024"
description = "Example REST service using rust-rest-macro"

[dependencies]
rust-rest-macro = { path = "../../crates/libs/rust-rest-macro" }
rust-jsonrpc-core = { path = "../../crates/libs/rust-jsonrpc-core" }
tokio = { workspace = true }
axum = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
schemars = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }