[package]
name = "ras-rest-macro"
version = "0.1.0"
edition = "2024"
description = "Procedural macro for type-safe REST APIs with auth integration and OpenAPI document generation"
license = "MIT OR Apache-2.0"
repository = "https://github.com/example/rust-agent-stack"
homepage = "https://github.com/example/rust-agent-stack"

[lib]
proc-macro = true

[features]
default = ["server", "client"]  # Enable server by default for backward compatibility
server = ["axum", "ras-auth-core", "ras-rest-core", "async-trait"]
client = ["reqwest"]

[dependencies]
syn = { workspace = true }
quote = { workspace = true }
proc-macro2 = { workspace = true }
serde = { workspace = true }
schemars = { workspace = true }

# Server dependencies
axum = { workspace = true, optional = true }
axum-extra.workspace = true
ras-auth-core = { path = "../../core/ras-auth-core", optional = true }
ras-rest-core = { path = "../ras-rest-core", optional = true }
async-trait = { workspace = true, optional = true }

# Client dependencies
reqwest = { workspace = true, optional = true }

[dev-dependencies]
tokio = { workspace = true }
wiremock = { workspace = true }
reqwest = { workspace = true }
tower = { workspace = true }
hyper = { workspace = true }
rand = { workspace = true }
ras-identity-session = { path = "../../identity/ras-identity-session" }
ras-jsonrpc-core = { path = "../../rpc/ras-jsonrpc-core" }
futures = { workspace = true }
chrono = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
async-trait = { workspace = true }
# Server dependencies for tests
axum = { workspace = true }
ras-auth-core = { path = "../../core/ras-auth-core" }
ras-rest-core = { path = "../ras-rest-core" }