[package]
name = "ras-observability-otel"
version = "0.1.0"
edition = "2024"
description = "OpenTelemetry implementation for Rust Agent Stack observability"

[dependencies]
ras-observability-core = { path = "../../core/ras-observability-core" }
ras-auth-core = { path = "../../core/ras-auth-core" }

# OpenTelemetry dependencies
opentelemetry = { workspace = true }
opentelemetry_sdk = { workspace = true }
opentelemetry-prometheus = { workspace = true }
prometheus = { workspace = true }

# Web framework and utilities
axum = { workspace = true }
async-trait = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["full", "macros", "rt-multi-thread"] }
tracing-subscriber = { workspace = true }

[[example]]
name = "simple_usage"
path = "examples/simple_usage.rs"

[[example]]
name = "with_rest_service"
path = "examples/with_rest_service.rs"