[package]
name = "bidirectional-chat-tui"
version = "0.1.0"
edition = "2024"

[dependencies]
# TUI framework
ratatui = { workspace = true }
crossterm = { workspace = true }

# Async runtime
tokio = { workspace = true, features = ["full"] }

# Chat API client
bidirectional-chat-api = { path = "../api" }

# Error handling
anyhow = { workspace = true }
thiserror = { workspace = true }

# HTTP client for auth
reqwest = { workspace = true, features = ["json"] }

# Serialization
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }

# Logging
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

# Time handling
chrono = { workspace = true }

# Configuration
dotenvy = { workspace = true }