[package]
name = "ras-jsonrpc-bidirectional-types"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
futures = { workspace = true }
thiserror = { workspace = true }
async-trait = { workspace = true }
tracing = { workspace = true }
ras-auth-core = { path = "../../../core/ras-auth-core" }
ras-jsonrpc-types = { path = "../../ras-jsonrpc-types" }
uuid = { workspace = true }
chrono = { workspace = true }

# WebSocket dependencies
tokio-tungstenite = { workspace = true }

[dev-dependencies]
tokio-test = { workspace = true }