[package]
name = "bidirectional-chat-server"
version = "0.1.0"
edition = "2024"

[dependencies]
# Local dependencies
bidirectional-chat-api = { path = "../api" }
ras-auth-core = { path = "../../../crates/libs/ras-auth-core" }
ras-jsonrpc-types = { path = "../../../crates/libs/ras-jsonrpc-types" }
ras-jsonrpc-bidirectional-macro = { path = "../../../crates/libs/ras-jsonrpc-bidirectional-macro" }
ras-jsonrpc-bidirectional-server = { path = "../../../crates/libs/ras-jsonrpc-bidirectional-server" }
ras-jsonrpc-bidirectional-types = { path = "../../../crates/libs/ras-jsonrpc-bidirectional-types" }
ras-identity-core = { path = "../../../crates/identity/ras-identity-core" }
ras-identity-local = { path = "../../../crates/identity/ras-identity-local" }
ras-identity-session = { path = "../../../crates/identity/ras-identity-session" }

# Workspace dependencies
axum = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
async-trait = { workspace = true }
chrono = { workspace = true }
uuid = { workspace = true }
dashmap = { workspace = true }
anyhow = { workspace = true }
tower-http = { workspace = true, features = ["cors"] }
dotenvy = { workspace = true }
jsonwebtoken = { workspace = true }
config = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
reqwest = { workspace = true, features = ["json"] }

[[bin]]
name = "test-config"
path = "src/bin/test_config.rs"

[features]
default = ["server"]
server = ["ras-jsonrpc-bidirectional-macro/server"]