name: Cargo Deny

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  schedule:
    # Run at 0900 UTC every Monday
    - cron: '0 9 * * 1'
  workflow_dispatch:

jobs:
  cargo-deny:
    name: Cargo Deny Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        checks:
          - advisories
          - bans
          - licenses
          - sources
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run cargo-deny
        uses: EmbarkStudios/cargo-deny-action@v1
        with:
          command: check ${{ matrix.checks }}
          arguments: --workspace

  cargo-deny-all:
    name: Cargo Deny Check All
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run cargo-deny (all checks)
        uses: EmbarkStudios/cargo-deny-action@v1
        with:
          command: check
          arguments: --workspace